/**
 * Generates and verifies the agent files that cannot be symlinks.
 *
 * Most agents read `AGENTS.md` and `.agents/skills/` through a symlink, so they never drift.
 * Two cases cannot. Gemini CLI loads one context file and has no on-demand skill loading, so
 * `GEMINI.md` is generated as `AGENTS.md` plus the conventions inlined. And every agent that
 * ships slash commands needs them in its own format, so the formats are checked for parity
 * rather than shared.
 *
 * Run `--write` to regenerate, or no argument to check, which is what CI runs.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

type CommandSet = {
  agent: string
  dir: string
  extension: string
}

const root = new URL('..', import.meta.url).pathname
const rulesDir = join(root, '.agents/skills/conventions/rules')
const geminiContext = join(root, 'GEMINI.md')

const commandSets: Array<CommandSet> = [
  { agent: 'claude', dir: 'tools/claude/commands', extension: '.md' },
  { agent: 'cursor', dir: 'tools/cursor/commands', extension: '.md' },
  { agent: 'gemini', dir: 'tools/gemini/commands', extension: '.toml' },
]

const stripFrontmatter = (source: string) => source.replace(/^---\n[\s\S]*?\n---\n/, '').trim()

const buildGeminiContext = () => {
  const rules = readdirSync(rulesDir)
    .filter((file) => file.endsWith('.md'))
    .sort()
    .map((file) => stripFrontmatter(readFileSync(join(rulesDir, file), 'utf8')))

  return [
    '<!-- Generated by scripts/agentFiles.ts. Edit AGENTS.md or the conventions rules instead. -->',
    '',
    readFileSync(join(root, 'AGENTS.md'), 'utf8').trim(),
    '',
    '# Conventions',
    '',
    'Gemini CLI has no on-demand skill loading, so the always-on conventions are inlined here.',
    '',
    ...rules,
    '',
  ].join('\n')
}

const commandNames = ({ dir, extension }: CommandSet) =>
  readdirSync(join(root, dir))
    .filter((file) => file.endsWith(extension))
    .map((file) => file.slice(0, -extension.length))
    .sort()

const checkCommandParity = () => {
  const [canonical, ...rest] = commandSets
  const expected = commandNames(canonical)

  return rest.flatMap((set) => {
    const actual = commandNames(set)
    const missing = expected.filter((name) => !actual.includes(name))
    const extra = actual.filter((name) => !expected.includes(name))

    return [
      ...missing.map((name) => `${set.agent} is missing the ${name} command`),
      ...extra.map((name) => `${set.agent} has ${name}, which ${canonical.agent} does not`),
    ]
  })
}

const write = () => {
  writeFileSync(geminiContext, buildGeminiContext())
  console.log('wrote GEMINI.md')
}

const check = () => {
  const problems = checkCommandParity()

  if (readFileSync(geminiContext, 'utf8') !== buildGeminiContext()) {
    problems.push('GEMINI.md is stale, run `pnpm agent-files --write`')
  }

  if (problems.length > 0) {
    console.error(problems.map((problem) => `- ${problem}`).join('\n'))
    process.exit(1)
  }

  console.log(`agent files in sync (${commandSets.length} command sets)`)
}

if (process.argv.includes('--write')) {
  write()
} else {
  check()
}
