name: Release
on:
  push:
    branches: [ 'main' ]
    paths:
      - '.changeset/**'
      - 'packages/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    if: github.repository_owner == 'stijnvanhulle'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      issues: write
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Tools
        uses: ./.github/setup
        with:
          node-version: '22'
          cache: 'false'

      - name: Build
        run: pnpm run build

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          version-script: pnpm run release:version
          publish-script: pnpm release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'ci(changesets): version packages'
          pr-title: 'ci(changesets): version packages'
        env:
          NPM_CONFIG_PROVENANCE: true
